- hosts: ambari-server
  become: true
  tasks:
  - name: "Register JAVA_HOME"
    shell: "cat /etc/ambari-server/conf/ambari.properties | grep '^java.home=' | cut -d '=' -f 2"
    register: java_home
- hosts: ambari-agent
  become: true
  tasks:
  - name: Download ssl cert targz from Ambari server
    shell: "curl -k -o /tmp/ssl.tar.gz '{{ ambari_protocol }}://{{ groups[['ambari-server'][0]][0] }}:{{ ambari_port }}/resources/ssl.tar.gz'"
  - file: path=/tmp/ssl state=absent
  - name: Untar ssl.tar.gz
    shell: "cd /tmp/ && tar -xzf ssl.tar.gz"
  - name: "Create keystore folders"
    file:
      path: "{{ ssl_ks_location }}"
      state: directory
      owner: "{{ remote_ambari_server_user }}"
      group: "{{ remote_ambari_server_group }}"
      mode: 0775
  - name: "Create truststore folders"
    file:
      path: "{{ ssl_ts_location }}"
      state: directory
      owner: "{{ remote_ambari_server_user }}"
      group: "{{ remote_ambari_server_group }}"
      mode: 0775
  - name: Copy host JKSs
    shell: "shost=$(echo `hostname -f` | cut -d . -f 1); cp -r /tmp/ssl/keys/${shost}.jks {{ ssl_ks_location }}/server.jks"
  - name: Copy host CERs
    shell: "shost=$(echo `hostname -f` | cut -d . -f 1); cp -r /tmp/ssl/cert/${shost}.cer {{ ssl_ks_location }}/server.pem"
  - name: Copy Truststore
    shell: "cp -r /tmp/ssl/truststore.jks {{ ssl_ts_location }}/truststore.jks"
  - name: Copy Truststore as ranger.jks
    shell: "cp -r /tmp/ssl/truststore.jks {{ ssl_ts_location }}/ranger-plugin.jks"
  - name: Copy cacerts
    shell: "cp /tmp/ssl/cacerts {{ hostvars[groups['ambari-server'][0]]['java_home']['stdout'] }}/jre/lib/security/cacerts && cp /tmp/ssl/cacerts /etc/pki/java/cacerts"
  - stat: path=/tmp/creds.jceks
    register: atlas_cred_var
  - name: Copy Atlas creds
    shell: "cp /tmp/creds.jceks /etc/pki/creds.jceks"
    when: atlas_cred_var.stat.exists

