- name: "Post Blueprint"
  become: true
  action: "shell sudo curl -X POST -v -k -u {{ ambari_username }}:{{ ambari_password }} -H 'X-Requested-By: ambari' {{ ambari_protocol }}://localhost:{{ ambari_port }}/api/v1/blueprints/myblueprint?validate_topology=false -d @/tmp/myblueprint.json"