- name: install the latest version of MySQL
  become: true
  yum:
    name: mysql-server
    state: latest
  when: ansible_distribution == 'CentOS' and ansible_distribution_version <= '7.0'
- name: install the MariaDB Server
  become: true
  yum:
    name: mariadb-server
    state: latest
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '7.0'
- name: install the MariaDB
  become: true
  yum:
    name: mariadb
    state: latest
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '7.0'
- name: Creates MySQL connector directory
  file: path=/opt/mysql-connectors state=directory
- name: install MySQL Java connector
  become: true
  get_url: url=http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.44/mysql-connector-java-5.1.44.jar  dest=/opt/mysql-connectors/mysql-connector-java.jar
- name: MySQL Start
  become: true
  service:
    name: mysqld
    state: started
  when: ansible_distribution == 'CentOS' and ansible_distribution_version <= '7.0'
- name: MariaDB Start
  become: true
  service:
    name: mariadb
    state: started
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '7.0'
