- hosts: ranger-admin # TODO: only works if you have a solr on your ranger admin host
  become: true
  become_user: infra-solr
  tasks:
    - name: "Get node details from zookeeper"
      action: "shell kinit -kt /etc/security/keytabs/ambari-infra-solr.service.keytab $(whoami)/$(hostname -f) && curl --negotiate -k -u : 'http://{{ inventory_hostname }}:8886/solr/admin/zookeeper?detail=true&path=%2Fcollections%2Franger_audits%2Fstate.json'"