# requires variables:
# - ambari_repo_base_url
# - ambari_version

- hosts: ambari-server ambari-agent
  become: true
  vars_prompt:
    - name: "ambari_repo_base_url"
      prompt: "Set ambari repo base url"
      private: no
  tasks:
    - include_tasks: ../roles/ambari-common/tasks/install-repo-{{ ansible_os_family }}.yml

- hosts: ambari-server
  become: true
  tasks:
    - include_tasks: ../roles/ambari-server/tasks/install-{{ ansible_os_family }}.yml
    - import_tasks: ../roles/ambari-server/tasks/setup.yml
    - import_tasks: ../roles/ambari-server/tasks/start.yml

- hosts: ambari-agent
  become: true
  tasks:
    - include_tasks: ../roles/ambari-agent/tasks/install-{{ ansible_os_family }}.yml
    - import_tasks: ../roles/ambari-agent/tasks/setup.yml
    - import_tasks: ../roles/ambari-agent/tasks/start.yml
